### ISSUE TITLE
Cannot find module 'fs-base'

### ISSUE THREAD

**Issue by rkmax** [archfirst/joinjs#12]
I just install joinjs, as soon start ugin got that message looking at the file 

    node_modules/joinjs/lib/index.js:1:72

I found

![image](https://cloud.githubusercontent.com/assets/395707/23513086/e45cda76-ff30-11e6-9af6-2e282fafbfe0.png)

but such module doesn't exist on npmjs

**Comment by nareshbhatia** [comment]
Are you sure you did `npm install --save join-js` with a dash in the middle?

**Comment by rkmax** [comment]
That was my error, thank you @nareshbhatia
