### ISSUE TITLE
Is the package being maintained?

### ISSUE THREAD

**Issue by FerrielMelarpis** [archfirst/joinjs#14]
Hi! First of all, what a great library! 
I like how you deal with the problem of mapping objects and sql results unlike the traditional ORM approach.
I like how it can just deal with the structure that I want to make by just using a configuration object.
This is what I do manually most of the times using db drivers, builders and lodash. 

_One thing though, is the package being maintained?_

I was thinking of incorporating this package into my projects but I doubt that this repo is being maintained? Also, do you have a roadmap that you can share for others to contribute as well?

I really hope that this push through as this is probably the best and simple solution for object-relation mapping I have researched yet.

**Comment by nareshbhatia** [comment]
Hi @FerrielMelarpis, thanks for the kind words.

To give you some context, this project started as a very simple utility when I was working on a project that used postgres. Unfortunately, I am currently not using relational DBs and there are other pressing priorities that are demanding my time.

Having said that the entire source is only 200 lines of code - with comments! It should not be too difficult to understand and extend. I would be happy to take PR's for enhancements/bug fixes, provided that existing tests don't fail and additional tests are provided for any functionality include in the PR.
