### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by FerrielMelarpis** [archfirst/joinjs#16]
It is probably a good idea to have one since this is a library that may soon be used by many developers.
Keeping all commits tested is one step to making sure of its quality.
Issues can be easily caught with regards to other versions of node js.
Also, we'll only be needing to review changes and not manually test it before merging.

**Comment by nareshbhatia** [comment]
Good idea, @FerrielMelarpis. On my to-do!

**Comment by nareshbhatia** [comment]
CI is now implemented. Yeah!

**Comment by FerrielMelarpis** [comment]
Nice!
