### ISSUE TITLE
Designed to work with multiple collections?

### ISSUE THREAD

**Issue by timruffles** [archfirst/joinjs#4]
Hi there - great work on joinjs.

One thing, let's say I do the following:

```sql
select A.A, B.B as B_B, C.C as C_C from A
left join B on ...
left join C on ... 
```
and get back

```sh
A   B   C
1   1   null
2   null 1
```
I'd expect to have `[ { A: 1, Bs: [{B: 1 }], Cs: [] }, { A: 2, Bs: [], Cs: [{C:1}] }]`, but currently I get `[ { A: 1, Bs: [{B:1}], Cs: [{C:null}}, ...` with the following JoinJS (might be slightly off, but you get the idea: I've done this correctly and end up with null rows for every top-level row which doesn't match all left joins)

```js
 [
    {
        mapId: 'A',
        idProperty: 'A',
        properties: ['A'],
        collections: [
            {name: 'Bs', mapId: 'B', columnPrefix: 'B_'},
            {name: 'Cs', mapId: 'C', columnPrefix: 'C_'}
        ]
    },
    {
        mapId: 'B',
        idProperty: 'B',
        properties: ['B']
    },
    {
        mapId: 'C',
        idProperty: 'C',
        properties: ['C']
    }
]
```

I couldn't see a test case that included a collections array of >1 element.

**Comment by nareshbhatia** [comment]
Interesting observation. Let me look into this.

**Comment by nareshbhatia** [comment]
Hi Tim, I just added a test for your use case and it seems to work fine. Check out the test here: https://github.com/archfirst/joinjs/blob/master/test/unit/mapper-test.js#L557-585. If your use case is different, please write a test for it. Note that I just fixed a couple of null related bugs, may be those were tripping up your example.

**Comment by timruffles** [comment]
Perfect. Yeah that was probably it, as I was getting objects with all
properties set to `null`. Thanks!
